global suppresssnap := false



QMK.SetupModifiers([
    ["a", "Ctrl"],
    ["s", "Shift"],
    ["d", "Win"],
    ["f", "Alt"],
    ["j", "Alt"],
    ["k", "Win"],
    ["l", "Shift"],
    [";", "Ctrl"],
])

QMK.SetupChords([
    ["a", "s", "c", "global", QMK.SendKeyDirect("^+c")],
    ["a", "s", "e", "global", QMK.SendKeyDirect("^+e")],
    ["a", "s", "r", "global", QMK.SendKeyDirect("^+r")],
    ["a", "s", "t", "global", QMK.SendKeyDirect("^+t")],
    ["a", "s", "y", "global", QMK.SendKeyDirect("^+y")],
    ["a", "s", "u", "global", QMK.SendKeyDirect("^+u")],
    ["a", "s", "i", "global", QMK.SendKeyDirect("^+i")],
    ["a", "s", "o", "global", QMK.SendKeyDirect("^+o")],
    ["a", "s", "p", "global", QMK.SendKeyDirect("^+p")],
    ["a", "s", "n", "global", QMK.SendKeyDirect("^+n")],
    ["a", "s", "m", "global", QMK.SendKeyDirect("^+m")],
    ["a", "s", "b", "global", QMK.SendKeyDirect("^+b")],
    ["a", "s", "v", "global", QMK.SendKeyDirect("^+v")],
    ["a", "s", "'", "global", QMK.SendKeyDirect("^{Delete}")],
    ["a", "s", ";", "global", QMK.SendKeyDirect("{Delete}")],
    ["a", "s", "]", "global", QMK.SendKeyDirect("^{Delete}")],
    ["a", "s", "l", "global", QMK.SendKeyDirect("^+{Right}")],
    ["a", "s", "h", "global", QMK.SendKeyDirect("^+{Left}")],
    ["a", "s", "k", "global", QMK.SendKeyDirect("+{Up}")],
    ["a", "s", "j", "global", QMK.SendKeyDirect("+{Down}")],
    ["a", "s", "g", "global", QMK.SendKeyDirect("+{End}")],
    [";", "l", "g", "global", QMK.SendKeyDirect("+{Home}")],
    [";", "l", "h", "global", QMK.SendKeyDirect("^+{Left}")],
    [";", "l", "Tab", "global", QMK.SendKeyDirect("^+{Tab}")],
    ["a", "d", "i", "global", QMK.SendKeyDirect("#{Tab}")]
])

QMK.SetupCombos([
    ["a", "h", "global", QMK.SendKeyDirect("^{Left}")],
    ["a", "k", "global", QMK.SendKeyDirect("{Up}")],
    ["a", "j", "global", QMK.SendKeyDirect("{Down}")],
    ["a", "l", "global", QMK.SendKeyDirect("^{Right}")],
    ["a", "[", "global", QMK.SendKeyDirect("{Delete}")],
    ["a", ";", "global", QMK.SendKeyDirect("{Backspace}"), "instant"],
    [";", "a", "global", QMK.SendKeyDirect("^a"), "instant"],
    ["a", "'", "global", QMK.SendKeyDirect("^{Backspace}"), "instant"],
    ["j", "Tab", "global", QMK.SendKeyDirect("!{Tab}"), "instant"],
    ["j", "k", "global", QMK.SendKeyDirect("{Esc}"), "instant"],
    ["k", "j", "global", QMK.SendKeyDirect("{Esc}"), "instant"],
    ["f", "[", "global", QMK.SendKeyDirect("^{PgUp}"), "instant"],
    ["f", "]", "global", QMK.SendKeyDirect("^{PgDn}"), "instant"],
    ["g", ";", "global", QMK.SendKeyDirect("^{Delete}"), "instant"],
    ["g", "'", "global", QMK.SendKeyDirect("^{Delete}"), "instant"],
    ; ["a", "f", "global", (*) => Qmk.SendDirect("^f")],
    ["z", "h", "global", QMK.SendKeyDirect("^+{Left}")],
    ["z", "k", "global", QMK.SendKeyDirect("+{Up}")],
    ["z", "j", "global", QMK.SendKeyDirect("+{Down}")],
    ["z", "l", "global", QMK.SendKeyDirect("^+{Right}")],
    ["z", "c", "global", QMK.SendKeyDirect("^c")],
    ["z", "x", "global", QMK.SendKeyDirect("^x")],
    ["z", "b", "global", QMK.SendKeyDirect("^b")],
    ["c", "n", "global", QMK.SendKeyDirect("1")],
    ["c", "m", "global", QMK.SendKeyDirect("1")],
    ["c", ",", "global", QMK.SendKeyDirect("2")],
    ["c", ".", "global", QMK.SendKeyDirect("3")],
    ["c", "j", "global", QMK.SendKeyDirect("4")],
    ["c", "k", "global", QMK.SendKeyDirect("5")],
    ["c", "l", "global", QMK.SendKeyDirect("6")],
    ["c", "u", "global", QMK.SendKeyDirect("7")],
    ["c", "i", "global", QMK.SendKeyDirect("8")],
    ["c", "o", "global", QMK.SendKeyDirect("9")],
    ["c", "Space", "global", QMK.SendKeyDirect("0")],
    ["c", ";", "global", QMK.SendKeyDirect("{Backspace}")],
    ["c", "'", "global", QMK.SendKeyDirect("^{Backspace}")],
    ["c", "[", "global", QMK.SendKeyDirect(".")],
    ["c", "/", "global", QMK.SendKeyDirect(".")],
    ["r", "n", "global", QMK.SendKeyDirect("+1")],
    ["r", "m", "global", QMK.SendKeyDirect("+1")],
    ["r", ",", "global", QMK.SendKeyDirect("+2")],
    ["r", ".", "global", QMK.SendKeyDirect("+3")],
    ["r", "j", "global", QMK.SendKeyDirect("+4")],
    ["r", "k", "global", QMK.SendKeyDirect("+5")],
    ["r", "l", "global", QMK.SendKeyDirect("+6")],
    ["r", "u", "global", QMK.SendKeyDirect("+7")],
    ["r", "i", "global", QMK.SendKeyDirect("+8")],
    ["r", "o", "global", QMK.SendKeyDirect("+9")],
    ["r", "Space", "global", QMK.SendKeyDirect("+0")],
    ["r", ";", "global", QMK.SendKeyDirect("+{-}")],
    ["t", "n", "global", QMK.SendKeyDirect("{F1}")],
    ["t", "m", "global", QMK.SendKeyDirect("{F1}")],
    ["t", ",", "global", QMK.SendKeyDirect("{F2}")],
    ["t", ".", "global", QMK.SendKeyDirect("{F3}")],
    ["t", "j", "global", QMK.SendKeyDirect("{F4}")],
    ["t", "k", "global", QMK.SendKeyDirect("{F5}")],
    ["t", "l", "global", QMK.SendKeyDirect("{F6}")],
    ["t", "u", "global", QMK.SendKeyDirect("{F7}")],
    ["t", "i", "global", QMK.SendKeyDirect("{F8}")],
    ["t", "o", "global", QMK.SendKeyDirect("{F9}")],
    ["t", "Space", "global", QMK.SendKeyDirect("{F10}")],
    ["t", ";", "global", QMK.SendKeyDirect("{F11}")],
    ["t", "'", "global", QMK.SendKeyDirect("{F12}")],
    ["g", "j", "global", QMK.SendKeyDirect("{Down}")],
    ["g", "k", "global", QMK.SendKeyDirect("{Up}")],
    ["g", "h", "global", QMK.SendKeyDirect("{Home}")],
    ["g", "l", "global", QMK.SendKeyDirect("{End}")],
    ["g", "u", "global", QMK.SendKeyDirect("^{Home}")],
    ["g", "n", "global", QMK.SendKeyDirect("^{End}")],
    ["g", "d", "global", QMK.SendKeyDirect("^{End}")],
    ["g", ";", "global", QMK.SendKeyDirect("{Delete}")],
    ["s", ";", "global", QMK.SendKeyDirect("+;")],
    ["s", "'", "global", QMK.SendKeyDirect("+'")],
    ["LAlt", ";", "global", QMK.SendKeyDirect("{Backspace}")],
    ["LAlt", "'", "global", QMK.SendKeyDirect("^{Backspace}")],
    ["f", "u", (*) => Send("{Browser_Back}")],  ; Browser_Back
    ["f", "p", (*) => Send("{Browser_Forward}")],
    ["v", "m", "global", (*) => media.volume.mute(), "instant"],
    ["v", "j", "global", (*) => media.volume.down(), "instant"],
    ["v", "k", "global", (*) => media.volume.up(), "instant"],
    ["v", "l", "global", (*) => media.next(), "instant"],
    ["v", "h", "global", (*) => media.previous(), "instant"],
    ["v", "p", "global", (*) => media.toggleplaypause(), "instant"],
    ["RAlt", "Left", "global", (*) => media.previous()],
    ["RAlt", "Right", "global", (*) => media.next()],
])

QMK.SetupChords([
    ["a", "f", "j", "", "", (*) => media.volume.down()],
    ["a", "f", "k", "", "", (*) => media.volume.up()],
    ["a", "f", "j", "", "", (*) => media.volume.down()],
    ["a", "f", "p", "", "", (*) => media.toggleplaypause()],
    ["a", "f", "Enter", "", "", (*) => media.toggleplaypause()],
    ["a", "f", "l", "", "", (*) => media.next()],
    ["a", "f", "h", "", "", (*) => media.previous()],
    ["a", "f", "y", "", "", (*) => globals.activaterun("Youtube Studio", "https://studio.youtube.com/channel/UCyUoNJYNIxfZMxV7g9_D4Sw/videos")],
; ============== Virtual Desktop Chords ==============
    ["a", "d", "j", "", "", (*) => (ToolTip("Desktop Closed!"), QMK.SendDirect("^#{F4}"), SetTimer(() => ToolTip(), -200))],
    ["a", "d", "k", "", "", (*) => (ToolTip("New Desktop!"), QMK.SendDirect("^#d"), SetTimer(() => ToolTip(), -200))],
    ["a", "s", "d", "f", "o", (*) => outlookdesktop.activate(true)],
    ["a", "s", "d", "l", "", (*) => ( VDA.MoveActiveToNext(),ToolTip(">>>> Moved to Right!"), SetTimer(() => ToolTip(), -200))],  ; asdl → next desktop
    ["a", "s", "d", "h", "", (*) => (VDA.MoveActiveToPrevious(), ToolTip("<<<< Moved to Left!") SetTimer(() => ToolTip(), -200))], ; asdh → previous desktop
    ["a", "d", "h", "", "", (*) => (VDA.GoLeft(), ToolTip("<<<< Moved Left!"), SetTimer(() => ToolTip(), -200))],
    ["a", "d", "l", "", "", (*) => (VDA.GoRight(), ToolTip(">>>> Moved Right!"), SetTimer(() => ToolTip(), -200))],

    ; special activations
    ["s", "f", "c", "", "", (*) => globals.activaterun("Google Calendar", "https://calendar.google.com/calendar/u/0/r")],
    ["s", "f", "g", "", "", (*) => globals.activaterun("Gmail", "https://mail.google.com")],
    ["s", "f", "h", "", "", (*) => media.connectheadphones()],
    ["s", "f", "j", "", "", (*) => globals.activaterun("ChatGPT", "https://chatgpt.com/?temporary-chat=true&model=gpt-5-instant")],
    ["s", "f", "k", "", "", (*) => globals.activaterun("Claude", "https://claude.ai/new")],
    ["s", "f", "l", "", "", (*) => fileexplorer.navrun(Libraries)],
    ["s", "f", "m", "", "", (*) => globals.activaterun("AMBOSS", "https://next.amboss.com/us")],
    ["s", "f", "n", "", "", (*) => notebooklm.quickcreate()],
    ["s", "f", "o", "", "", (*) => onenote.activate(true)],
    ["s", "f", "p", "", "", (*) => globals.activaterun("Spotify for Creators", "https://creators.spotify.com/pod/show/7lNvdBsvWKhblGyVn80JTo/episodes?pageSize=30")],
    ["s", "f", "r", "", "", (*) => globals.activaterun("Reddit", "https://www.reddit.com/")],
    ["s", "f", "t", "", "", (*) => SendAsPaste(FormatTime(A_Now, "MM.dd.yyyy"))],
    ["s", "f", "y", "", "", (*) => globals.activaterun("Youtube", "https://www.youtube.com")],
])



QMK.SetupCombos([
    ["a", "u", (*) => mm.GestureUL()],
    ["b", "1", (*) => globals.activaterun("Organ Systems", os_url, false)],
    ["b", "o", (*) => globals.activaterun("Organ Systems", os_url, false)],
    ["b", "2", (*) => globals.activaterun("Osteopathic Principles", opp_url, false)],
    ["b", "n", (*) => globals.activaterun("Osteopathic Principles", opp_url, false)],
    ["b", "3", (*) => globals.activaterun("Physician Core Competencies", pcc_url, false)],
    ["b", "c", (*) => globals.activaterun("Physician Core Competencies", pcc_url, false)],
    ["b", "4", (*) => globals.activaterun("Principles of Clinical Medicine", pcm_url, false)],
    ["b", "m", (*) => globals.activaterun("Principles of Clinical Medicine", pcm_url, false)],
    ["b", "5", (*) => (globals.activaterun("Research Princinciples", rp_journal_url, false), Run(rp_other_url))],
    ["b", "r", (*) => (globals.activaterun("Research Princinciples", rp_journal_url, false), Run(rp_other_url))],
    ["b", "6", (*) => globals.activaterun("Special Topics", st_url, false)],
    ["b", "s", (*) => globals.activaterun("Special Topics", st_url, false)],
    ["b", "a", (*) => baptistrunall()],
    ["b", "g", (*) => globals.activaterun("GroupMe", "https://web.groupme.com/chats")],
    ["b", "j", (*) => Brightness.AdjustScreenBrightness(-6)],
    ["b", "k", (*) => Brightness.AdjustScreenBrightness(6)],
    ["b", "p", (*) => ShowMenuWithDigits(MenuMap["pollev"])],
    ["b", "t", (*) => FunRun(tbl2_url)],
    ["b", "w", (*) => FunRun("https://www.webpathology.com/images/genitourinary/kidney/renal-cell-carcinomas---i/35906")],

    ["c", "Enter",  (*) => mouse.click("c")],   ; sends {Click}

    ["d", "g", (*) => mm.ThrowLeft()],
    ["d", ";", (*) => mm.ThrowRight()],
    ["d", "h", (*) => mm.SnapLeft()],
    ["d", "l", (*) => mm.SnapRight("A")],
    ["d", "j", (*) => mm.GestureDL()],
    ["d", "k", (*) => mm.GestureUR()],
    ["d", "'", (*) => globals.teleport()],
    ["d", "u", (*) => mm.GestureUL()],
    ["d", "n", (*) => mm.GestureDL()],
    ["d", ".", (*) => mm.GestureDR()],
    ["d", "o", (*) => mm.GestureUR()],
    ["f", "i", (*) => Scroll.up()],
    ["f", "m", (*) => Scroll.left()],
    ["f", ".", (*) => Scroll.right()],

    ["f", "l", (*) => mouse.move("l")],
    ["f", "j", (*) => mouse.move("j")],
    ["f", "k", (*) => mouse.move("k")],
    ["f", "h", (*) => mouse.move("h")],
    ["f", "'", (*) => globals.teleport()],
    ["f", "m", (*) => globals.teleport()],

    ["f", ",", "global", (*) => SetTimer(() => Scroll.Down(), -1), "instant"],

    ["f", "n", (*) => SetTimer(() => mouse.click("d"), -1)],
    ["f", "Enter", (*) => SetTimer(() => mouse.quickclick(), -1)],
    ; p
    ["p", "a", (*) => anki.activate(true)],
    ["p", "z", (*) => zen.activate(true)],
    ["p", "s", (*) => spotify.activate(true)],
    ["p", "l", (*) => logi.activate(true)],
    ["p", "m", (*) => messenger.activate(true)],
    ["p", "w", (*) => word.activate()],
    ["p", "d", (*) => runchecklist()],
    ["p", "o", (*) => Onenote.activate(true)],
    ["p", "u", (*) => outlookdesktop.activate(true)],
    ; w
    ["w", "a", (*) => ShowMenuWithDigits(MenuMap["audiobooks"])],
    ["w", "c", (*) => chatgpt.screenshot()],
    ["w", "d", (*) => globals.activaterun("Google Docs", "https://docs.google.com/")],
    ["w", "g", (*) => globals.activaterun("Google", "https://www.google.com")],
    ["w", "i", (*) => globals.activaterun("Intedashboard", "https://v3.intedashboard.com/in/tests")],
    ["w", "j", (*) => globals.activaterun("ChatGPT", "https://chatgpt.com/?temporary-chat=true&model=gpt-5-instant")],
    ["w", "k", (*) => globals.activaterun("Claude", "https://claude.ai/new")],
    ["w", "n", (*) => globals.activaterun("NotebookLM", "https://notebooklm.google.com/")],
    ["w", "r", (*) => globals.activaterun("Grok", "https://grok.com")],
    ["w", "s", (*) => globals.activaterun("Church of Jesus Christ", "https://www.churchofjesuschrist.org")],
    ["w", "t", (*) => chatgpt.screenshot()],
    ["w", "p", (*) => globals.activaterun("Spotify for Creators", "https://creators.spotify.com/pod/show/7lNvdBsvWKhblGyVn80JTo/episodes?pageSize=30")],
    ["w", "y", (*) => globals.activaterun("Youtube", "https://www.youtube.com")],
    [".", "l", (*) => Spotify.PlayPlaylist("Liked Songs")],
    [".", "b", (*) => Spotify.PlayPlaylist("This Is Benson Boone")],
    [".", "m", (*) => Spotify.OpenGenericMedSchoolPodcast()],
    [".", "d", (*) => Spotify.PlayPlaylist("The Stormlight Archive - Brandon Sanderson - Fantasy Reading Music")],
    [".", "t", (*) => Spotify.PlayPlaylist("This Is The Tabernacle Choir at Temple Square")],
    [".", "n", (*) => Spotify.PlayPlaylist("no words movie songs for studying")],
    [".", "g", (*) => Spotify.PlayPlaylist("Best Studio Ghibli Soundtracks ✨")],
    ; x - window movement
    ["x", "h", (*) => mm.ThrowLeft()],
    ["x", "l", (*) => mm.ThrowRight()],
    ["x", "j", (*) => mm.GestureDL()],
    ["x", "k", (*) => mm.GestureUR()],
    ["x", "g", (*) => mm.SnapLeft()],
    ["x", ";", (*) => mm.SnapRight()],
    ["m", "h", (*) => mm.ThrowLeft()],
    ["m", "l", (*) => mm.ThrowRight()],
])
QMK.SetupHolds([
    ["a", ["global"], (*) => anki.activate(true)],
    ["b", ["global"], (*) => ShowMenuWithDigits(MenuMap["bucom"])],
    ["c", ["global"], (*) => globals.activaterun("Google Calendar", "https://calendar.google.com/calendar/u/0/r")],
    ["d", ["global"], (*) => runchecklist2()],
    ["e", ["global"], (*) => edge.activate(true)],
    ["f", ["global"], (*) => globals.activaterun("ChatGPT", "https://chatgpt.com/?temporary-chat=true")],
    ["g", ["global"], (*) => globals.activaterun("Gmail", "https://mail.google.com/mail/u/0/#inbox")],
    ["h", ["global"], (*) => mm.SnapLeft()],
    ["i", ["global"], (*) => globals.activaterun("ChatGPT", "https://chatgpt.com/?temporary-chat=true")],
    ["j", ["ahk_exe ONENOTE.EXE"], (*) => onenote.GestureDL()],
    ["j", ["global"], (*) => mm.GestureDL()],
    ["j", ["Med School - Anki"], (*) => Anki.GestureDL()],
    ["k", ["ahk_exe ONENOTE.EXE"], (*) => onenote.GestureUR()],
    ["k", ["Med School - Anki"], (*) => Anki.GestureUR()],
    ["k", ["global"], (*) => mm.GestureUR()],
    ["l", ["global"], (*) => mm.SnapRight("A")],
    ["m", ["global"], (*) => globals.teleport()],
    ["n", ["global"], (*) => mm.GestureDL()],
    ["o", ["global"], (*) => Onenote.activate(true)],
    ["p", ["global"], (*) => phonelink.activate(true)],
    ["q", ["global"], (*) => (globals.quitminimize())],
    ["r", ["global"], (*) => QMK.SendDirect("^{Home}")],   ; Ctrl + Home
    ["s", ["global"], (*) => spotify.activate(true)],
    ["t", ["global"], (*) => Run(lib "\Simple Timer.ahk")],
    ["u", ["global"], (*) => mm.GestureUL()],
    ["v", ["global"], (*) => vscode.activate(true)],
    ["w", ["global"], (*) => QMK.SendDirect("^w")],   ; Ctrl + W
    ["x", ["global"], (*) => SecondaryMenus()],
    ["y", ["global"], (*) => globals.activaterun("Youtube", "https://www.youtube.com")],
    ["Tab", ["global"], (*) => QMK.SendDirect("!{Tab}")],   ; Alt + Tab
    ["z", ["global"], (*) => globals.teleport()],
    [",", ["global"], (*) => SetTimer(() => Scroll.Down(), -1)],
    ["[", ["global"], (*) => ShowMenuWithDigits(MenuMap["programs"])],
    [".", ["global"], (*) => mm.GestureDR()],
    [";", ["global"], (*) => ShowMenuWithDigits(MenuMap["Spotify"])],
    ["Enter", ["global"], (*) => QMK.SendDirect("{Enter}")],   ; Enter down
])


; QMK.SetupHolds([
;     ["p", ["ahk_class #32768"], (*) => media.previous()],
;     ["l", ["ahk_class #32768"], (*) => (ToolTip(">>>> Moved Right!"), QMK.SendDirect("^#{Right}"), SetTimer((*) => ToolTip(), -1000))],
;     ["h", ["ahk_class #32768"], (*) => (ToolTip("<<<< Moved Left!"), QMK.SendDirect("^#{Left}"), SetTimer((*) => ToolTip(), -1000))],
;     ["k", ["ahk_class #32768"], (*) => (ToolTip("New Desktop!"), QMK.SendDirect("^#d"), SetTimer((*) => ToolTip(), -1000))],
;     ["j", ["ahk_class #32768"], (*) => (ToolTip("Closed Desktop!"), QMK.SendDirect("^#{F4}"), SetTimer((*) => ToolTip(), -1000))],
;     ["s", ["ahk_class #32768"], (*) => (churchofjesuschrist.opencurrentspot())],
;     ["g", ["ahk_class #32768"], (*) => (churchofjesuschrist.opencurrentspot("generalconference"))],
; ])

QMK.SetupCombos([
    ["]", "1", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.AnswerLearningObjectives, , , "LO", 1)],
    ["]", "2", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.AnswerLearningObjectives, , , "LO", 2)],
    ["]", "3", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.AnswerLearningObjectives, , , "LO", 3)],
    ["]", "4", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.AnswerLearningObjectives, , , "LO", 4)],
    ["]", "5", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.AnswerLearningObjectives, , , "LO", 5)],
    ["]", "6", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.AnswerLearningObjectives, , , "LO", 6)],
    ["]", "7", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.AnswerLearningObjectives, , , "LO", 7)],
    ["]", "8", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.AnswerLearningObjectives, , , "LO", 8)],
    ["]", "9", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.AnswerLearningObjectives, , , "LO", 9)],
    ["]", "0", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.AnswerLearningObjectives, , , "LO", 10)],
    ["[", "1", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.PathLearningObjectives, , , "PLO", 1)],
    ["[", "2", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.PathLearningObjectives, , , "PLO", 2)],
    ["[", "3", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.PathLearningObjectives, , , "PLO", 3)],
    ["[", "4", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.PathLearningObjectives, , , "PLO", 4)],
    ["[", "5", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.PathLearningObjectives, , , "PLO", 5)],
    ["[", "6", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.PathLearningObjectives, , , "PLO", 6)],
    ["[", "7", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.PathLearningObjectives, , , "PLO", 7)],
    ["[", "8", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.PathLearningObjectives, , , "PLO", 8)],
    ["[", "9", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.PathLearningObjectives, , , "PLO", 9)],
    ["[", "0", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.PathLearningObjectives, , , "PLO", 10)],
    ["c", "1", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 1)],
    ["c", "2", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 2)],
    ["c", "3", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 3)],
    ["c", "4", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 4)],
    ["c", "5", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 5)],
    ["c", "6", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 6)],
    ["c", "7", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 7)],
    ["c", "8", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 8)],
    ["c", "9", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 9)],
    ["c", "0", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 10)],
    ["t", "1", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.pharmtable, , , "PT", 1)],
    ["t", "2", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.pharmtable, , , "PT", 2)],
    ["t", "3", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.pharmtable, , , "PT", 3)],
    ["t", "4", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.pharmtable, , , "PT", 4)],
    ["t", "5", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.pharmtable, , , "PT", 5)],
    ["t", "6", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.pharmtable, , , "PT", 6)],
    ["t", "7", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.pharmtable, , , "PT", 7)],
    ["t", "8", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.pharmtable, , , "PT", 8)],
    ["t", "9", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.pharmtable, , , "PT", 9)],
    ["t", "0", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.pharmtable, , , "PT", 10)],
    ["a", "1", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 1)],
    ["a", "2", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 2)],
    ["a", "3", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 3)],
    ["a", "4", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 4)],
    ["a", "5", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 5)],
    ["a", "6", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 6)],
    ["a", "7", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 7)],
    ["a", "8", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 8)],
    ["a", "9", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 9)],
    ["a", "0", (*) => chatgpt.opentabgroups("https://chatgpt.com/?model=gpt-5-instant", Prompts.Cloze5, , , "Cloze", 10)],
    ["n", "1", (*) => notebooklm.opentabgroups(url := "https://notebooklm.google.com", prompt := Prompts.NotebookLMGenerate, , , "NBLM", 1)],
    ["n", "2", (*) => notebooklm.opentabgroups(url := "https://notebooklm.google.com", prompt := Prompts.NotebookLMGenerate, , , "NBLM", 2, true)],
    ["n", "3", (*) => notebooklm.opentabgroups(url := "https://notebooklm.google.com", prompt := Prompts.NotebookLMGenerate, , , "NBLM", 3, true)],
    ["n", "4", (*) => notebooklm.opentabgroups(url := "https://notebooklm.google.com", prompt := Prompts.NotebookLMGenerate, , , "NBLM", 4, true)],
    ["n", "5", (*) => notebooklm.opentabgroups(url := "https://notebooklm.google.com", prompt := Prompts.NotebookLMGenerate, , , "NBLM", 5, true)],
    ["n", "6", (*) => notebooklm.opentabgroups(url := "https://notebooklm.google.com", prompt := Prompts.NotebookLMGenerate, , , "NBLM", 6, true)],
    ["n", "7", (*) => notebooklm.opentabgroups(url := "https://notebooklm.google.com", prompt := Prompts.NotebookLMGenerate, , , "NBLM", 7, true)],
    ["n", "8", (*) => notebooklm.opentabgroups(url := "https://notebooklm.google.com", prompt := Prompts.NotebookLMGenerate, , , "NBLM", 8, true)],
    ["n", "9", (*) => notebooklm.opentabgroups(url := "https://notebooklm.google.com", prompt := Prompts.NotebookLMGenerate, , , "NBLM", 9, true)],
    ["n", "0", (*) => notebooklm.opentabgroups(url := "https://notebooklm.google.com", prompt := Prompts.NotebookLMGenerate, , , "NBLM", 10, true)],
    ["p", "1", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/7lNvdBsvWKhblGyVn80JTo/episode/wizard", "", true, "", "SP", 1)],
    ["p", "2", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/7lNvdBsvWKhblGyVn80JTo/episode/wizard", "", true, "", "SP", 2)],
    ["p", "3", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/7lNvdBsvWKhblGyVn80JTo/episode/wizard", "", true, "", "SP", 3)],
    ["p", "4", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/7lNvdBsvWKhblGyVn80JTo/episode/wizard", "", true, "", "SP", 4)],
    ["p", "5", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/7lNvdBsvWKhblGyVn80JTo/episode/wizard", "", true, "", "SP", 5)],
    ["p", "6", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/7lNvdBsvWKhblGyVn80JTo/episode/wizard", "", true, "", "SP", 6)],
    ["p", "7", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/7lNvdBsvWKhblGyVn80JTo/episode/wizard", "", true, "", "SP", 7)],
    ["p", "8", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/7lNvdBsvWKhblGyVn80JTo/episode/wizard", "", true, "", "SP", 8)],
    ["p", "9", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/7lNvdBsvWKhblGyVn80JTo/episode/wizard", "", true, "", "SP", 9)],
    ["p", "0", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/7lNvdBsvWKhblGyVn80JTo/episode/wizard", "", true, "", "SP", 10)],
    ["j", "1", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/70CMf86AxUZNXXHsmTW2KK/episode/wizard", "", true, "", "SP", 1)],
    ["j", "2", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/70CMf86AxUZNXXHsmTW2KK/episode/wizard", "", true, "", "SP", 2)],
    ["j", "3", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/70CMf86AxUZNXXHsmTW2KK/episode/wizard", "", true, "", "SP", 3)],
    ["j", "4", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/70CMf86AxUZNXXHsmTW2KK/episode/wizard", "", true, "", "SP", 4)],
    ["j", "5", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/70CMf86AxUZNXXHsmTW2KK/episode/wizard", "", true, "", "SP", 5)],
    ["j", "6", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/70CMf86AxUZNXXHsmTW2KK/episode/wizard", "", true, "", "SP", 6)],
    ["j", "7", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/70CMf86AxUZNXXHsmTW2KK/episode/wizard", "", true, "", "SP", 7)],
    ["j", "8", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/70CMf86AxUZNXXHsmTW2KK/episode/wizard", "", true, "", "SP", 8)],
    ["j", "9", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/70CMf86AxUZNXXHsmTW2KK/episode/wizard", "", true, "", "SP", 9)],
    ["j", "0", (*) => spotifypodcast.opentabgroups("https://creators.spotify.com/pod/show/70CMf86AxUZNXXHsmTW2KK/episode/wizard", "", true, "", "SP", 10)],
])



    ; --- LCtrl double-tap ---
QMK.SetupDoubleTaps([
    ["LCtrl", ["baptistu.instructure.com/login/ldap"], (*) => canvas.Btsi2()],
    ["LCtrl", ["baptistu.instructure.com"], (*) => ShowMenuWithDigits(MenuMap["bucom"])],
    ["LCtrl", ["baptistu.one45.com/index.php?login_message"], (*) => one45.login()],
    ["LCtrl", ["baptistu.one45.com/"], (*) => one45.mycalendar()],
    ["LCtrl", ["Med School - Anki"], (*) => chatgpt.editscreenshotinanki()],
    ["LCtrl", ["Add ahk_exe anki.exe"], (*) => Anki.ClickImageOcclusion()],
    ["LCtrl", ["Browse ahk_exe anki.exe"], (*) => Anki.StripClozeFormatting()],
    ["LCtrl", ["Edit Current"], (*) => Anki.StripClozeFormatting()],
    ["LCtrl", ["Image Occlusion Enhanced - Add Mode"], (*) => Anki.AddModeAndClose()],
    ["LCtrl", ["Select an Image"], (*) => QMK.SendDirect("^q")],
    ["LCtrl", ["next.amboss.com"], (*) => chatgpt.editscreenshotinanki()],
    ["LCtrl", ["ankiuser.net"], (*) => bwe([{ LocalizedType: "button", Name: "Show Answer" }], "Invoke")],
    ["LCtrl", ["audible.com"], (*) => audible.togglenarationspeed()],
    ["LCtrl", ["chatgpt.com"], (*) => chatgpt.editscreenshotinanki()],
    ["LCtrl", ["Name File"], (*) => chatgpt.setnamefilevalueasonenote()],
    ["LCtrl", ["claude.ai"], (*) => claude.switchbrowsers()],
    ["LCtrl", ["churchofjesuschrist.org"], (*) => churchofjesuschrist.togglenarationspeed()],
    ["LCtrl", ["grok.com"], (*) => grok.switchbrowsers()],
    ["LCtrl", ["groupme.com"], (*) => phonelink.activate(true)],
    ["LCtrl", ["docs.google.com/forms"], (*) => googleforms.defaultbudgetform()],
    ["LCtrl", ["mail.google.com/mail/u/0/#inbox"], (*) => gmail.delete()],
    ["LCtrl", ["calendar.google.com/calendar/u/0/r/eventedit"], (*) => googlecalendar.addemailnotifications()],
    ["LCtrl", ["drive.google.com"], (*) => googledrive.delete()],
    ["LCtrl", ["contacts.google.com"], (*) => googlecontacts.messagetophonelink()],
    ["LCtrl", ["notebooklm.google.com"], (*) => notebooklm.setaioverview(true, "Default")],
    ["LCtrl", ["intedashboard.com"], (*) => intedashboard.Click("Save Answer")],
    ["LCtrl", ["login.microsoftonline.com"], (*) => canvas.Btsi()],
    ["LCtrl", ["microsoft.com"], (*) => bwe({ Name: "Sign in" })],
    ["LCtrl", ["outlook.live.com"], (*) => (QMK.SendDirect("^w"), outlookdesktop.activate(true))],   ; Ctrl + W    QMK.SetupDoubleTap("LCtrl", ["pathoma.com"], (*) => pathoma.login())
    ["LCtrl", ["redketchup.io"], (*) => redketchup.converttoico()],
    ["LCtrl", ["open.spotify.com"], (*) => spotifyforweb.openindesktop()],
    ["LCtrl", ["creators.spotify.com/pod/show"], (*) => spotifypodcast.onenoteinfototitleandschedule()],
    ["LCtrl", ["uccu.com"], (*) => SetTimer(() => globals.activaterun("Gmail", "https://mail.google.com"))],
    ["LCtrl", ["webpathology.com"], (*) => webpathology.next()],
    ["LCtrl", ["webpath.med.utah.edu"], (*) => webpath.next()],
    ["LCtrl", ["youtube.com"], (*) => chatgpt.editscreenshotinanki()],
    ["LCtrl", ["Save As"], (*) => fileexplorer.saveasonenotepagetitle()],
    ["LCtrl", ["ahk_class CabinetWClass"], (*) => fileexplorer.saveasonenotepagetitle()],
    ["LCtrl", ["Hotstring Helper ahk_class AutoHotkeyGUI"], (*) => bwe({ LocalizedType: "button", Name: "Hide/Show Completed" }, "Click")],
    ["LCtrl", ["ahk_exe ONENOTE.EXE"], (*) => chatgpt.editscreenshotinanki()],
    ["LCtrl", ["ahk_exe PhoneExperienceHost.exe"], (*) => phonelink.newmessage("Linsey Hafen", "7346211818")],
    ["LCtrl", ["ahk_exe Code.exe"], (*) => vscode.reducedoubleclick()],
    ["LAlt", ["Add ahk_exe anki.exe"], (*) => Anki.ToggleBasicAndAnking()],
    ["RShift", ["ahk_exe Code.exe"], (*) => vscode.nextmatch()],
    ["RShift", ["ahk_exe ONENOTE.EXE"], (*) => (ToolTip("Syncing!"), SetTimer(() => ToolTip(), -500), Send("+{F9}"))],   ; Shift + F9
])


QMK.SetupCombos([
    ["CapsLock", "a", "global", (*) => anki.activate(true)],
    ["CapsLock", "b", "global", (*) => ShowMenuWithDigits(MenuMap["bucom"])],
    ["CapsLock", "c", "global", (*) => globals.activaterun("Google Calendar", "https://calendar.google.com/calendar/u/0/r")],
    ["CapsLock", "d", "global", (*) => runchecklist()],
    ["CapsLock", "e", "global", (*) => edge.activate(true)],
    ["CapsLock", "f", "global", (*) => globals.activaterun("ChatGPT", "https://chatgpt.com/?temporary-chat=true")],
    ["CapsLock", "g", "global", QMK.SendKeyDirect("^g")],


    ["CapsLock", "r", "global", QMK.SendKeyDirect("^{Home}")],   ; Ctrl + Home
    ["CapsLock", "t", "global", QMK.SendKeyDirect("^t")],   ; Ctrl + T
    ["CapsLock", "u", "global", (*) => mm.GestureUL()],
    ["CapsLock", "v", "global", QMK.SendKeyDirect("^v")],   ; Ctrl + V
    ["CapsLock", "w", "global", QMK.SendKeyDirect("^w")],   ; Ctrl + W
    ["CapsLock", "x", "global", (*) => SecondaryMenus()],
    ["CapsLock", "y", "global", (*) => globals.activaterun("Youtube", "https://www.youtube.com")],
    ["CapsLock", "z", "global", (*) => globals.teleport()],

    ["CapsLock", "h", "global", QMK.SendKeyDirect("^{h}"), "instant"],
    ["CapsLock", "i", "global", QMK.SendKeyDirect("^{i}"), "instant"],
    ["CapsLock", "j", "global", QMK.SendKeyDirect("^{j}"), "instant"],
    ["CapsLock", "k", "global", QMK.SendKeyDirect("^{k}"), "instant"],
    ["CapsLock", "l", "global", QMK.SendKeyDirect("^{l}"), "instant"],
    ["CapsLock", "m", "global", QMK.SendKeyDirect("^{m}"), "instant"],
    ["CapsLock", "n", "global", QMK.SendKeyDirect("^{n}"), "instant"],
    ["CapsLock", "o", "global", QMK.SendKeyDirect("^{o}"), "instant"],
    ["CapsLock", "p", "global", QMK.SendKeyDirect("^{p}"), "instant"],

    ["CapsLock", "Tab", "global", QMK.SendKeyDirect("!{Tab}")],   ; Alt + Tab
    ["CapsLock", ",", "global", (*) => SetTimer(() => Scroll.Down(), -1)],
    ["CapsLock", "[", "global", (*) => ShowMenuWithDigits(MenuMap["programs"])],
    ["CapsLock", ".", "global", (*) => mm.GestureDR()],
])



QMK.SetupChords([
    ["CapsLock", "LAlt", "h", "", "", (*) => mm.SnapLeft()],
    ["CapsLock", "LAlt", "j", "", "", (*) => mm.GestureD()],
    ["CapsLock", "LAlt", "k", "", "", (*) => mm.GestureUR()],
    ["CapsLock", "LAlt", "l", "", "", (*) => mm.SnapRight()],
    ["CapsLock", "LAlt", "Left", "", "", (*) => mm.SnapLeft()],
    ["CapsLock", "LAlt", "Down", "", "", (*) => mm.GestureD()],
    ["CapsLock", "LAlt", "Up", "", "", (*) => mm.GestureUR()],
    ["CapsLock", "LAlt", "Right", "", "", (*) => mm.SnapRight()],
    ; switch desktop
    ["CapsLock", "s", "h", "", "", (*) => (ToolTip("<<<< Moved Left!"), QMK.SendDirect("^#{Left}"), SetTimer(() => ToolTip(), -1000))],
    ["CapsLock", "s", "j", "", "", (*) => (ToolTip("Desktop Closed!"), QMK.SendDirect("^#{F4}"), SetTimer(() => ToolTip(), -1000))],
    ["CapsLock", "s", "k", "", "", (*) => (ToolTip("New Desktop!"), QMK.SendDirect("^#d"), SetTimer(() => ToolTip(), -1000))],
    ["CapsLock", "s", "l", "", "", (*) => (ToolTip(">>>> Moved Right!"), QMK.SendDirect("^#{Right}"), SetTimer(() => ToolTip(), -1000))],
])



; Timers:
; timers
QMK.SetupCombos([
    ["1", "m", (*) => (Run(lib "\Simple Timer.ahk 1"), SetTimer((*) => ToolTip(), -1000), ToolTip("1 minute timer started!"))],
    ["2", "m", (*) => (Run(lib "\Simple Timer.ahk 2"), SetTimer((*) => ToolTip(), -1000), ToolTip("2 minute timer started!"))],
    ["3", "m", (*) => (Run(lib "\Simple Timer.ahk 3"), SetTimer((*) => ToolTip(), -1000), ToolTip("3 minute timer started!"))],
    ["4", "m", (*) => (Run(lib "\Simple Timer.ahk 4"), SetTimer((*) => ToolTip(), -1000), ToolTip("4 minute timer started!"))],
    ["5", "m", (*) => (Run(lib "\Simple Timer.ahk 5"), SetTimer((*) => ToolTip(), -1000), ToolTip("5 minute timer started!"))],
    ["6", "m", (*) => (Run(lib "\Simple Timer.ahk 6"), SetTimer((*) => ToolTip(), -1000), ToolTip("6 minute timer started!"))],
    ["7", "m", (*) => (Run(lib "\Simple Timer.ahk 7"), SetTimer((*) => ToolTip(), -1000), ToolTip("7 minute timer started!"))],
    ["8", "m", (*) => (Run(lib "\Simple Timer.ahk 8"), SetTimer((*) => ToolTip(), -1000), ToolTip("8 minute timer started!"))],
    ["9", "m", (*) => (Run(lib "\Simple Timer.ahk 9"), SetTimer((*) => ToolTip(), -1000), ToolTip("9 minute timer started!"))],
    ["1", "h", (*) => (Run(lib "\Simple Timer.ahk 60"), SetTimer((*) => ToolTip(), -1000), ToolTip("1 hour timer started!"))],
    ["2", "h", (*) => (Run(lib "\Simple Timer.ahk 120"), SetTimer((*) => ToolTip(), -1000), ToolTip("2 hour timer started!"))],
    ["3", "h", (*) => (Run(lib "\Simple Timer.ahk 180"), SetTimer((*) => ToolTip(), -1000), ToolTip("3 hour timer started!"))],
    ["4", "h", (*) => (Run(lib "\Simple Timer.ahk 240"), SetTimer((*) => ToolTip(), -1000), ToolTip("4 hour timer started!"))],
    ["5", "h", (*) => (Run(lib "\Simple Timer.ahk 300"), SetTimer((*) => ToolTip(), -1000), ToolTip("5 hour timer started!"))],
    ["6", "h", (*) => (Run(lib "\Simple Timer.ahk 360"), SetTimer((*) => ToolTip(), -1000), ToolTip("6 hour timer started!"))],
    ["7", "h", (*) => (Run(lib "\Simple Timer.ahk 420"), SetTimer((*) => ToolTip(), -1000), ToolTip("7 hour timer started!"))],
    ["8", "h", (*) => (Run(lib "\Simple Timer.ahk 480"), SetTimer((*) => ToolTip(), -1000), ToolTip("8 hour timer started!"))],
    ["9", "h", (*) => (Run(lib "\Simple Timer.ahk 540"), SetTimer((*) => ToolTip(), -1000), ToolTip("9 hour timer started!"))],
    ["1", "0", (*) => (Run(lib "\Simple Timer.ahk 10"), SetTimer((*) => ToolTip(), -1000), ToolTip("10 minute timer started!"))],
    ["1", "2", (*) => (Run(lib "\Simple Timer.ahk 12"), SetTimer((*) => ToolTip(), -1000), ToolTip("12 minute timer started!"))],
    ["1", "3", (*) => (Run(lib "\Simple Timer.ahk 13"), SetTimer((*) => ToolTip(), -1000), ToolTip("13 minute timer started!"))],
    ["1", "4", (*) => (Run(lib "\Simple Timer.ahk 14"), SetTimer((*) => ToolTip(), -1000), ToolTip("14 minute timer started!"))],
    ["1", "5", (*) => (Run(lib "\Simple Timer.ahk 15"), SetTimer((*) => ToolTip(), -1000), ToolTip("15 minute timer started!"))],
    ["1", "6", (*) => (Run(lib "\Simple Timer.ahk 16"), SetTimer((*) => ToolTip(), -1000), ToolTip("16 minute timer started!"))],
    ["1", "7", (*) => (Run(lib "\Simple Timer.ahk 17"), SetTimer((*) => ToolTip(), -1000), ToolTip("17 minute timer started!"))],
    ["1", "8", (*) => (Run(lib "\Simple Timer.ahk 18"), SetTimer((*) => ToolTip(), -1000), ToolTip("18 minute timer started!"))],
    ["1", "9", (*) => (Run(lib "\Simple Timer.ahk 19"), SetTimer((*) => ToolTip(), -1000), ToolTip("19 minute timer started!"))],
    ["2", "0", (*) => (Run(lib "\Simple Timer.ahk 20"), SetTimer((*) => ToolTip(), -1000), ToolTip("20 minute timer started!"))],
    ["2", "1", (*) => (Run(lib "\Simple Timer.ahk 21"), SetTimer((*) => ToolTip(), -1000), ToolTip("21 minute timer started!"))],
    ["2", "3", (*) => (Run(lib "\Simple Timer.ahk 23"), SetTimer((*) => ToolTip(), -1000), ToolTip("23 minute timer started!"))],
    ["2", "4", (*) => (Run(lib "\Simple Timer.ahk 24"), SetTimer((*) => ToolTip(), -1000), ToolTip("24 minute timer started!"))],
    ["2", "5", (*) => (Run(lib "\Simple Timer.ahk 25"), SetTimer((*) => ToolTip(), -1000), ToolTip("25 minute timer started!"))],
    ["2", "6", (*) => (Run(lib "\Simple Timer.ahk 26"), SetTimer((*) => ToolTip(), -1000), ToolTip("26 minute timer started!"))],
    ["2", "7", (*) => (Run(lib "\Simple Timer.ahk 27"), SetTimer((*) => ToolTip(), -1000), ToolTip("27 minute timer started!"))],
    ["2", "8", (*) => (Run(lib "\Simple Timer.ahk 28"), SetTimer((*) => ToolTip(), -1000), ToolTip("28 minute timer started!"))],
    ["2", "9", (*) => (Run(lib "\Simple Timer.ahk 29"), SetTimer((*) => ToolTip(), -1000), ToolTip("29 minute timer started!"))],
    ["3", "0", (*) => (Run(lib "\Simple Timer.ahk 30"), SetTimer((*) => ToolTip(), -1000), ToolTip("30 minute timer started!"))],
    ["3", "1", (*) => (Run(lib "\Simple Timer.ahk 31"), SetTimer((*) => ToolTip(), -1000), ToolTip("31 minute timer started!"))],
    ["3", "2", (*) => (Run(lib "\Simple Timer.ahk 32"), SetTimer((*) => ToolTip(), -1000), ToolTip("32 minute timer started!"))],
    ["3", "4", (*) => (Run(lib "\Simple Timer.ahk 34"), SetTimer((*) => ToolTip(), -1000), ToolTip("34 minute timer started!"))],
    ["3", "5", (*) => (Run(lib "\Simple Timer.ahk 35"), SetTimer((*) => ToolTip(), -1000), ToolTip("35 minute timer started!"))],
    ["3", "6", (*) => (Run(lib "\Simple Timer.ahk 36"), SetTimer((*) => ToolTip(), -1000), ToolTip("36 minute timer started!"))],
    ["3", "7", (*) => (Run(lib "\Simple Timer.ahk 37"), SetTimer((*) => ToolTip(), -1000), ToolTip("37 minute timer started!"))],
    ["3", "8", (*) => (Run(lib "\Simple Timer.ahk 38"), SetTimer((*) => ToolTip(), -1000), ToolTip("38 minute timer started!"))],
    ["3", "9", (*) => (Run(lib "\Simple Timer.ahk 39"), SetTimer((*) => ToolTip(), -1000), ToolTip("39 minute timer started!"))],
    ["4", "0", (*) => (Run(lib "\Simple Timer.ahk 40"), SetTimer((*) => ToolTip(), -1000), ToolTip("40 minute timer started!"))],
    ["4", "1", (*) => (Run(lib "\Simple Timer.ahk 41"), SetTimer((*) => ToolTip(), -1000), ToolTip("41 minute timer started!"))],
    ["4", "2", (*) => (Run(lib "\Simple Timer.ahk 42"), SetTimer((*) => ToolTip(), -1000), ToolTip("42 minute timer started!"))],
    ["4", "3", (*) => (Run(lib "\Simple Timer.ahk 43"), SetTimer((*) => ToolTip(), -1000), ToolTip("43 minute timer started!"))],
    ["4", "5", (*) => (Run(lib "\Simple Timer.ahk 45"), SetTimer((*) => ToolTip(), -1000), ToolTip("45 minute timer started!"))],
    ["4", "6", (*) => (Run(lib "\Simple Timer.ahk 46"), SetTimer((*) => ToolTip(), -1000), ToolTip("46 minute timer started!"))],
    ["4", "7", (*) => (Run(lib "\Simple Timer.ahk 47"), SetTimer((*) => ToolTip(), -1000), ToolTip("47 minute timer started!"))],
    ["4", "8", (*) => (Run(lib "\Simple Timer.ahk 48"), SetTimer((*) => ToolTip(), -1000), ToolTip("48 minute timer started!"))],
    ["4", "9", (*) => (Run(lib "\Simple Timer.ahk 49"), SetTimer((*) => ToolTip(), -1000), ToolTip("49 minute timer started!"))],
    ["5", "0", (*) => (Run(lib "\Simple Timer.ahk 50"), SetTimer((*) => ToolTip(), -1000), ToolTip("50 minute timer started!"))],
    ["5", "1", (*) => (Run(lib "\Simple Timer.ahk 51"), SetTimer((*) => ToolTip(), -1000), ToolTip("51 minute timer started!"))],
    ["5", "2", (*) => (Run(lib "\Simple Timer.ahk 52"), SetTimer((*) => ToolTip(), -1000), ToolTip("52 minute timer started!"))],
    ["5", "3", (*) => (Run(lib "\Simple Timer.ahk 53"), SetTimer((*) => ToolTip(), -1000), ToolTip("53 minute timer started!"))],
    ["5", "4", (*) => (Run(lib "\Simple Timer.ahk 54"), SetTimer((*) => ToolTip(), -1000), ToolTip("54 minute timer started!"))],
    ["5", "6", (*) => (Run(lib "\Simple Timer.ahk 56"), SetTimer((*) => ToolTip(), -1000), ToolTip("56 minute timer started!"))],
    ["5", "7", (*) => (Run(lib "\Simple Timer.ahk 57"), SetTimer((*) => ToolTip(), -1000), ToolTip("57 minute timer started!"))],
    ["5", "8", (*) => (Run(lib "\Simple Timer.ahk 58"), SetTimer((*) => ToolTip(), -1000), ToolTip("58 minute timer started!"))],
    ["5", "9", (*) => (Run(lib "\Simple Timer.ahk 59"), SetTimer((*) => ToolTip(), -1000), ToolTip("59 minute timer started!"))],
    ["6", "0", (*) => (Run(lib "\Simple Timer.ahk 60"), SetTimer((*) => ToolTip(), -1000), ToolTip("60 minute timer started!"))],
    ["6", "1", (*) => (Run(lib "\Simple Timer.ahk 61"), SetTimer((*) => ToolTip(), -1000), ToolTip("61 minute timer started!"))],
    ["6", "2", (*) => (Run(lib "\Simple Timer.ahk 62"), SetTimer((*) => ToolTip(), -1000), ToolTip("62 minute timer started!"))],
    ["6", "3", (*) => (Run(lib "\Simple Timer.ahk 63"), SetTimer((*) => ToolTip(), -1000), ToolTip("63 minute timer started!"))],
    ["6", "4", (*) => (Run(lib "\Simple Timer.ahk 64"), SetTimer((*) => ToolTip(), -1000), ToolTip("64 minute timer started!"))],
    ["6", "5", (*) => (Run(lib "\Simple Timer.ahk 65"), SetTimer((*) => ToolTip(), -1000), ToolTip("65 minute timer started!"))],

    ["6", "7", (*) => (Run(lib "\Simple Timer.ahk 67"), SetTimer((*) => ToolTip(), -1000), ToolTip("67 minute timer started!"))],
    ["6", "8", (*) => (Run(lib "\Simple Timer.ahk 68"), SetTimer((*) => ToolTip(), -1000), ToolTip("68 minute timer started!"))],
    ["6", "9", (*) => (Run(lib "\Simple Timer.ahk 69"), SetTimer((*) => ToolTip(), -1000), ToolTip("69 minute timer started!"))],
    ["7", "0", (*) => (Run(lib "\Simple Timer.ahk 70"), SetTimer((*) => ToolTip(), -1000), ToolTip("70 minute timer started!"))],
    ["7", "1", (*) => (Run(lib "\Simple Timer.ahk 71"), SetTimer((*) => ToolTip(), -1000), ToolTip("71 minute timer started!"))],
    ["7", "2", (*) => (Run(lib "\Simple Timer.ahk 72"), SetTimer((*) => ToolTip(), -1000), ToolTip("72 minute timer started!"))],
    ["7", "3", (*) => (Run(lib "\Simple Timer.ahk 73"), SetTimer((*) => ToolTip(), -1000), ToolTip("73 minute timer started!"))],
    ["7", "4", (*) => (Run(lib "\Simple Timer.ahk 74"), SetTimer((*) => ToolTip(), -1000), ToolTip("74 minute timer started!"))],
    ["7", "5", (*) => (Run(lib "\Simple Timer.ahk 75"), SetTimer((*) => ToolTip(), -1000), ToolTip("75 minute timer started!"))],
    ["7", "6", (*) => (Run(lib "\Simple Timer.ahk 76"), SetTimer((*) => ToolTip(), -1000), ToolTip("76 minute timer started!"))],

    ["7", "8", (*) => (Run(lib "\Simple Timer.ahk 78"), SetTimer((*) => ToolTip(), -1000), ToolTip("78 minute timer started!"))],
    ["7", "9", (*) => (Run(lib "\Simple Timer.ahk 79"), SetTimer((*) => ToolTip(), -1000), ToolTip("79 minute timer started!"))],
    ["8", "0", (*) => (Run(lib "\Simple Timer.ahk 80"), SetTimer((*) => ToolTip(), -1000), ToolTip("80 minute timer started!"))],
    ["8", "1", (*) => (Run(lib "\Simple Timer.ahk 81"), SetTimer((*) => ToolTip(), -1000), ToolTip("81 minute timer started!"))],
    ["8", "2", (*) => (Run(lib "\Simple Timer.ahk 82"), SetTimer((*) => ToolTip(), -1000), ToolTip("82 minute timer started!"))],
    ["8", "3", (*) => (Run(lib "\Simple Timer.ahk 83"), SetTimer((*) => ToolTip(), -1000), ToolTip("83 minute timer started!"))],
    ["8", "4", (*) => (Run(lib "\Simple Timer.ahk 84"), SetTimer((*) => ToolTip(), -1000), ToolTip("84 minute timer started!"))],
    ["8", "5", (*) => (Run(lib "\Simple Timer.ahk 85"), SetTimer((*) => ToolTip(), -1000), ToolTip("85 minute timer started!"))],
    ["8", "6", (*) => (Run(lib "\Simple Timer.ahk 86"), SetTimer((*) => ToolTip(), -1000), ToolTip("86 minute timer started!"))],
    ["8", "7", (*) => (Run(lib "\Simple Timer.ahk 87"), SetTimer((*) => ToolTip(), -1000), ToolTip("87 minute timer started!"))],

    ["8", "9", (*) => (Run(lib "\Simple Timer.ahk 89"), SetTimer((*) => ToolTip(), -1000), ToolTip("89 minute timer started!"))],
    ["9", "0", (*) => (Run(lib "\Simple Timer.ahk 90"), SetTimer((*) => ToolTip(), -1000), ToolTip("90 minute timer started!"))],
    ["9", "1", (*) => (Run(lib "\Simple Timer.ahk 91"), SetTimer((*) => ToolTip(), -1000), ToolTip("91 minute timer started!"))],
    ["9", "2", (*) => (Run(lib "\Simple Timer.ahk 92"), SetTimer((*) => ToolTip(), -1000), ToolTip("92 minute timer started!"))],
    ["9", "3", (*) => (Run(lib "\Simple Timer.ahk 93"), SetTimer((*) => ToolTip(), -1000), ToolTip("93 minute timer started!"))],
    ["9", "4", (*) => (Run(lib "\Simple Timer.ahk 94"), SetTimer((*) => ToolTip(), -1000), ToolTip("94 minute timer started!"))],
    ["9", "5", (*) => (Run(lib "\Simple Timer.ahk 95"), SetTimer((*) => ToolTip(), -1000), ToolTip("95 minute timer started!"))],
    ["9", "6", (*) => (Run(lib "\Simple Timer.ahk 96"), SetTimer((*) => ToolTip(), -1000), ToolTip("96 minute timer started!"))],
    ["9", "7", (*) => (Run(lib "\Simple Timer.ahk 97"), SetTimer((*) => ToolTip(), -1000), ToolTip("97 minute timer started!"))],
    ["9", "8", (*) => (Run(lib "\Simple Timer.ahk 98"), SetTimer((*) => ToolTip(), -1000), ToolTip("98 minute timer started!"))],
])


; website combos
; QMK.SetupCombos[(
; ["a", "f", (*) =>  Send("{Blind}/") ] ; combos do not let you do it context specific


; )]
; #HotIf WinActive("Med School - Anki")  && Qmk.NoModifiers()
; ~l:: {
;     global ldowntime
;     ldowntime := A_TickCount
; }
; ~l up:: {
;     global luptime, ldowntime, suppresssnap
;     luptime := A_TickCount
;     if !suppresssnap {
;         ((luptime - ldowntime) > 200) ? mm.snapright() : Send("{Enter}")
;     } else {
;         suppresssnap := false
;     }
; }
; ~j & tab:: Send("!{Tab}"), suppresssnap := true
; ~j:: {
;     global ldowntime
;     ldowntime := A_TickCount
; }
; ~j up:: {
;     global luptime, ldowntime, suppresssnap
;     luptime := A_TickCount
;     if !suppresssnap {
;         ((luptime - ldowntime) > 200) ? mm.GestureD() : Send("2")
;     } else {
;         suppresssnap := false
;     }
; }
; #HotIf
